package com.mycompany.app.lcdc;
/* CVS $Id: $ */

import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from /Users/betwar-mac/desktop/workspacejava/ttl/domain-slice.ttl 
 * @author Auto-generated by schemagen on 25 Oct 2015 12:39 
 */
public class domainSlice {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/sstats/lcdc/def/domain-slice#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Resource ThemeSlice = m_model.createResource( "http://purl.org/sstats/lcdc/def/domain-slice#ThemeSlice" );
    
}
