package com.mycompany.app.lcdc;
import com.hp.hpl.jena.ontology.DatatypeProperty;
import com.hp.hpl.jena.ontology.OntClass;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.ModelFactory;

import com.hp.hpl.jena.rdf.model.Resource;


import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from core.ttl
 * @author Auto-generated by schemagen on 08 Sep 2015 01:02
 */
public class LcdcCore {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/sstats/lcdc/def/core#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    public static final ObjectProperty node = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/core#node"
);

    public static final ObjectProperty obsInterval = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/core#obsInterval" );

    public static final ObjectProperty phase = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/core#phase" );

    public static final ObjectProperty phaseInterval = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/core#phaseInterval" );

    public static final ObjectProperty protocol = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/core#protocol" );

    public static final ObjectProperty study = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/core#study" );

    public static final ObjectProperty studyInterval = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/core#studyInterval" );

    public static final ObjectProperty subject = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/core#subject" );

    public static final DatatypeProperty gender = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#gender" );

    public static final DatatypeProperty nodeKey = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#nodeKey" );

    public static final DatatypeProperty obsDate = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#obsDate" );

    public static final DatatypeProperty obsTime = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#obsTime" );

    public static final DatatypeProperty phaseKey = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#phaseKey" );

    public static final DatatypeProperty questionKey = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#questionKey" );

    public static final DatatypeProperty questionnaireKey = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#questionnaireKey" );

    public static final DatatypeProperty studyKey = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#studyKey" );

    public static final DatatypeProperty subjectKey = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#subjectKey" );

    public static final DatatypeProperty themeId = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#themeId" );

    public static final DatatypeProperty variableDefinitionKey = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#variableDefinitionKey" );

    public static final DatatypeProperty variableId = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/core#variableId" );

    public static final OntClass DataFile = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#DataFile" );

    public static final OntClass Node = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#Node" );

    public static final OntClass Phase = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#Phase" );

    public static final OntClass Protocol = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#Protocol" );

    public static final OntClass Question = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#Question" );

    public static final OntClass Questionnaire = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#Questionnaire" );

    public static final OntClass Study = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#Study" );

    public static final OntClass StudyGroup = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#StudyGroup" );

    public static final OntClass Subject = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#Subject" );

    public static final OntClass Theme = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#Theme" );

    public static final OntClass Variable = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#Variable" );

    public static final OntClass VariableDefinition = m_model.createClass( "http://purl.org/sstats/lcdc/def/core#VariableDefinition" );

    public static final Resource nodecode = m_model.createResource( "http://purl.org/sstats/lcdc/def/core#nodecode" );

    public static final Resource phasecode = m_model.createResource( "http://purl.org/sstats/lcdc/def/core#phasecode" );


    public static final Resource questioncode = m_model.createResource( "http://purl.org/sstats/lcdc/def/core#questioncode" );

    public static final Resource questionnairecode = m_model.createResource( "http://purl.org/sstats/lcdc/def/core#questionnairecode" );

    public static final Resource studycode = m_model.createResource( "http://purl.org/sstats/lcdc/def/core#studycode" );


    public static final Resource subjectcode = m_model.createResource( "http://purl.org/sstats/lcdc/def/core#subjectcode" );

    public static final Resource themecode = m_model.createResource( "http://purl.org/sstats/lcdc/def/core#themecode" );


    public static final Resource variablecode = m_model.createResource( "http://purl.org/sstats/lcdc/def/core#variablecode" );

    public static final Resource variabledefinitioncode = m_model.createResource( "http://purl.org/sstats/lcdc/def/core#variabledefinitioncode" );

}