package com.mycompany.app.lcdc;


import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from obs.ttl
 * @author Auto-generated by schemagen on 07 Sep 2015 22:38
 */
public class Obs {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/sstats/lcdc/def/obs#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    public static final ObjectProperty END_INSTANT = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/obs#endInstant" );

    public static final ObjectProperty START_INSTANT = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/obs#startInstant" );

    public static final DatatypeProperty CUBE_OBS_MISSING = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#cubeObsMissing" );

    public static final DatatypeProperty DAY = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#day" );

    public static final DatatypeProperty END_DAY = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#endDay" );

    public static final DatatypeProperty END_MONTH = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#endMonth" );

    public static final DatatypeProperty END_YEAR = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#endYear" );

    public static final DatatypeProperty HOUR = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#hour" );

    public static final DatatypeProperty MINUTE = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#minute" );

    public static final DatatypeProperty MONTH = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#month" );

    public static final DatatypeProperty OBS_DATE_TIME = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#obsDateTime" );

    public static final DatatypeProperty OBS_DURATION = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#obsDuration" );

    public static final DatatypeProperty SECOND = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#second" );

    public static final DatatypeProperty START_DAY = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#startDay" );

    public static final DatatypeProperty START_MONTH = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#startMonth" );

    public static final DatatypeProperty START_YEAR = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#startYear" );

    public static final DatatypeProperty YEAR = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#year" );

    public static final OntClass DATED_OBSERVATION = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#DatedObservation" );

    public static final OntClass DATED_OBSERVATION_GROUP = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#DatedObservationGroup" );

    public static final OntClass INTERVAL_OBSERVATION = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#IntervalObservation" );

    public static final OntClass INTERVAL_OBSERVATION_GROUP = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#IntervalObservationGroup" );

    public static final OntClass OBSERVATION = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#Observation" );

    public static final OntClass OBSERVATION_GROUP = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#ObservationGroup" );

    public static final OntClass TIMED_OBSERVATION = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#TimedObservation" );

    public static final OntClass TIMED_OBSERVATION_GROUP = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#TimedObservationGroup" );

}
