package com.mycompany.app.lcdc;

import com.hp.hpl.jena.ontology.DatatypeProperty;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;



/**
 * Vocabulary definitions from file:C:\Users\abbas\Desktop\EclipseMarsWorkSpace\odm-project\1.1.1\src/main/java/odm.ttl 
 * @author Auto-generated by schemagen on 31 Aug 2015 23:40 
 */
public class Odm {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/sstats/lcdc/def/odm#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
   
    public static final DatatypeProperty ItemOid = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#ItemOid" );
    
    public static final DatatypeProperty comment = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#comment" );
    
    public static final DatatypeProperty dataType = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#dataType" );
    
    public static final DatatypeProperty formOid = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#formOid" );
    
    public static final DatatypeProperty formType = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#formType" );
    
    public static final DatatypeProperty itemGroupOid = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#itemGroupOid" );
    
    public static final DatatypeProperty itemtext = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#itemtext" );
    
    public static final DatatypeProperty nodeOid = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#nodeOid" );
    
    public static final DatatypeProperty repeating = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#repeating" );
    
    public static final DatatypeProperty sectiontext = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#sectiontext" );
    
    public static final DatatypeProperty studyEventOid = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#studyEventOid" );
    
    public static final DatatypeProperty studyOID = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#studyOID" );
    
    public static final DatatypeProperty subjectKey = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/odm#subjectKey" );
    
}
