package com.mycompany.app.lcdc;
/* CVS $Id: $ */

import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from /Users/betwar-mac/desktop/workspacejava/ttl/time-series.ttl 
 * @author Auto-generated by schemagen on 25 Oct 2015 12:40 
 */
public class timeSeries {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/sstats/lcdc/def/time-series#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Resource DatedPhaseSeries = m_model.createResource( "http://purl.org/sstats/lcdc/def/time-series#DatedPhaseSeries" );
    
    public static final Resource DatedSeries = m_model.createResource( "http://purl.org/sstats/lcdc/def/time-series#DatedSeries" );
    
    public static final Resource IntervalSeries = m_model.createResource( "http://purl.org/sstats/lcdc/def/time-series#IntervalSeries" );
    
    public static final Resource NestedSeries = m_model.createResource( "http://purl.org/sstats/lcdc/def/time-series#NestedSeries" );
    
    public static final Resource ObsSeries = m_model.createResource( "http://purl.org/sstats/lcdc/def/time-series#ObsSeries" );
    
    public static final Resource PhaseSeries = m_model.createResource( "http://purl.org/sstats/lcdc/def/time-series#PhaseSeries" );
    
    public static final Resource Series = m_model.createResource( "http://purl.org/sstats/lcdc/def/time-series#Series" );
    
    public static final Resource ThemeSeries = m_model.createResource( "http://purl.org/sstats/lcdc/def/time-series#ThemeSeries" );
    
    public static final Resource TimedSeries = m_model.createResource( "http://purl.org/sstats/lcdc/def/time-series#TimedSeries" );
    
}
