package au.csiro.aehrc.app.lcdc;


import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from obs.ttl
 * @author generated by Abbas.H.Safaie on 07 Sep 2015 22:38
 * @author Designed by  hugo leroux
 * 
 * @prefix apivc: <http://purl.org/linked-data/api/vocab#> .
	@prefix atcddd: <http://www.whocc.no/atc#> .
	@prefix cc: <http://creativecommons.org/ns#> .
	@prefix cdiscdef: <http://purl.org/odm2rdf/cdisc/def/cdisc#> .
	@prefix cdiscs: <http://purl.org/odm2rdf/cdisc/schema#> .
	@prefix cdiscuniverse: <http://purl.org/odm2rdf/cdisc/id/universe/> .
	@prefix cdiscvariable: <http://purl.org/odm2rdf/cdisc/id/variable/> .
	@prefix cm: <http://purl.org/sstats/lcdc/cm/def/cm#> .
	@prefix cmamt: <http://purl.org/sstats/lcdc/cm/def/cm-amt#> .
	@prefix cmatc: <http://purl.org/sstats/lcdc/cm/def/cm-atc#> .
	@prefix cmsnomed: <http://purl.org/sstats/lcdc/cm/def/cm-snomed#> .
	@prefix ct: <http://rdf.cdisc.org/sdtm/ct#> .
	@prefix cts: <http://rdf.cdisc.org/ct/schema#> .
	@prefix dc: <http://purl.org/dc/elements/1.1/> .
	@prefix dcterms: <http://purl.org/dc/terms/> .
	@prefix disco: <http://rdf-vocabulary.ddialliance.org/discovery#> .
	@prefix interval: <http://reference.data.gov.uk/def/intervals/> .
	@prefix lcdcaibl: <http://purl.org/sstats/lcdc/def/aibl#> .
	@prefix lcdccore: <http://purl.org/sstats/lcdc/def/core#> .
	@prefix lcdccube: <http://purl.org/sstats/lcdc/def/cube#> .
	@prefix lcdcobs: <http://purl.org/sstats/lcdc/def/obs#> .
	@prefix lcdcodm: <http://purl.org/sstats/lcdc/def/odm#> .
	@prefix lcdcsection: <http://purl.org/sstats/lcdc/def/cross-section#> .
	@prefix lcdcseries: <http://purl.org/sstats/lcdc/def/time-series#> .
	@prefix lcdcslice: <http://purl.org/sstats/lcdc/def/domain-slice#> .
	@prefix mms: <http://rdf.cdisc.org/mms#> .
	@prefix owl: <http://www.w3.org/2002/07/owl#> .
	@prefix prov: <http://www.w3.org/ns/prov#> .
	@prefix qb: <http://purl.org/linked-data/cube#> .
	@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
	@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
	@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
	@prefix ssn: <http://purl.oclc.org/NET/ssnx/ssn#> .
	@prefix summarystats: <http://rdf-vocabulary.ddialliance.org/summary-stats#> .
	@prefix time: <http://www.w3.org/2006/time#> .
	@prefix void: <http://rdfs.org/ns/void#> .
	@prefix xml: <http://www.w3.org/XML/1998/namespace> .
	@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
	
	cc:license a owl:AnnotationProperty .
	
	dc:creator a owl:AnnotationProperty .
	
	dc:date a owl:AnnotationProperty .
	
	dc:description a owl:AnnotationProperty .
	
	dc:identifier a owl:AnnotationProperty .
	
	dc:rights a owl:AnnotationProperty .
	
	dc:source a owl:AnnotationProperty .
	
	dc:title a owl:AnnotationProperty .
	
	dcterms:modified a owl:AnnotationProperty .
	
	apivc:uriTemplate a owl:AnnotationProperty .
	
	<http://purl.org/sstats/lcdc/def/obs> a owl:Ontology ;
	    cc:license <http://creativecommons.org/licenses/by/3.0/au/> ;
	    dc:creator "Hugo Leroux, The Australian E-Health Research Centre, CSIRO"^^xsd:string ;
	    dc:date "2015-07-10" ;
	    dc:description "Linked Clinical Data Cube Observation ontology" ;
	    dc:rights "Copyright 2013 CSIRO." ;
	    dc:title "Linked Clinical Data Cube Observation ontology" ;
	    dcterms:modified "2015-07-10" ;
	    void:uriSpace "http://purl.org/sstats/lcdc/def/obs#" .
	
	lcdcobs:IntervalObservation a owl:Class ;
	    rdfs:label "Interval Observation" ;
	    dc:description "Specialised cube observation for which a date and a time are available (will be used for cases where the same observations is done at different times during the day)." ;
	    apivc:uriTemplate "http://aehrc-ci.it.csiro.au/dataset/aibl/{linked}/theme/{theme}/subtheme/{subtheme}/phase/{phase}/subject/{subject}/interval/{interval}" ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:subClassOf [ a owl:Restriction ;
	            owl:onProperty lcdccore:obsInterval ;
	            owl:someValuesFrom interval:CalendarInterval ],
	        [ a owl:Restriction ;
	            owl:onProperty lcdcobs:endInstant ;
	            owl:someValuesFrom interval:CalendarInstant ],
	        [ a owl:Restriction ;
	            owl:onProperty lcdcobs:startInstant ;
	            owl:someValuesFrom interval:CalendarInstant ],
	        lcdcobs:Observation .
	
	lcdcobs:IntervalObservationGroup a owl:Class ;
	    rdfs:label "Interval Observation Group" ;
	    dc:description "Main cube observation group (and observation) for which collection interval data is available: contains links to all the specialised timed cube observations (will be used for cases where the same observations is done at different times during the day)." ;
	    apivc:uriTemplate "http://aehrc-ci.it.csiro.au/dataset/aibl/{linked}/phase/{phase}/subject/{subject}/interval/{interval}/time/{time}" ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:subClassOf lcdcobs:ObservationGroup .
	
	lcdcobs:TimedObservation a owl:Class ;
	    rdfs:label "Timed Observation" ;
	    dc:description "Specialised cube observation for which a date and a time are available (will be used for cases where the same observations is done at different times during the day)." ;
	    apivc:uriTemplate "http://aehrc-ci.it.csiro.au/dataset/aibl/{linked}/theme/{theme}/subtheme/{subtheme}/phase/{phase}/subject/{subject}/date/{date}/time/{time}" ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:subClassOf lcdcobs:DatedObservation .
	
	lcdcobs:TimedObservationGroup a owl:Class ;
	    rdfs:label "Timed Observation Group" ;
	    dc:description "Main cube observation group (and observation) for which a date and a time are available: contains links to all the specialised timed cube observations (will be used for cases where the same observations is done at different times during the day)." ;
	    apivc:uriTemplate "http://aehrc-ci.it.csiro.au/dataset/aibl/{linked}/phase/{phase}/subject/{subject}/date/{date}/time/{time}" ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:subClassOf lcdcobs:DatedObservationGroup .
	
	lcdcobs:cubeObsMissing a owl:DatatypeProperty ;
	    rdfs:label "cube observation missing" ;
	    dc:description "Flag to record the presence or absence of the specialised observation" ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:boolean .
	
	lcdcobs:day a owl:DatatypeProperty ;
	    rdfs:label "day" ;
	    dc:description "The day of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:endDay a owl:DatatypeProperty ;
	    rdfs:label "end day" ;
	    dc:description "The end day of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:endMonth a owl:DatatypeProperty ;
	    rdfs:label "end month" ;
	    dc:description "The end month of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:endYear a owl:DatatypeProperty ;
	    rdfs:label "end year" ;
	    dc:description "The end year of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:hour a owl:DatatypeProperty ;
	    rdfs:label "hour" ;
	    dc:description "The hour of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:minute a owl:DatatypeProperty ;
	    rdfs:label "minute" ;
	    dc:description "The minute of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:month a owl:DatatypeProperty ;
	    rdfs:label "month" ;
	    dc:description "The month of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:obsDateTime a owl:DatatypeProperty ;
	    rdfs:label "obs date time" ;
	    dc:description "The date of collection of the observation data," ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:dateTime .
	
	lcdcobs:obsDuration a owl:DatatypeProperty ;
	    rdfs:label "obs duration" ;
	    dc:description "The duration of the interval during which the data has been sampled." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:duration .
	
	lcdcobs:second a owl:DatatypeProperty ;
	    rdfs:label "second" ;
	    dc:description "The second of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:startDay a owl:DatatypeProperty ;
	    rdfs:label "start day" ;
	    dc:description "The day of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:startMonth a owl:DatatypeProperty ;
	    rdfs:label "start month" ;
	    dc:description "The month of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:startYear a owl:DatatypeProperty ;
	    rdfs:label "start year" ;
	    dc:description "The start year of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	lcdcobs:year a owl:DatatypeProperty ;
	    rdfs:label "year" ;
	    dc:description "The year of the observation, when available." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:range xsd:integer .
	
	qb:ObservationGroup a owl:Class .
	
	qb:dataSet a owl:ObjectProperty .
	
	qb:specialisedObservation a owl:ObjectProperty .
	
	lcdccore:Node a owl:Class .
	
	lcdccore:Phase a owl:Class .
	
	lcdccore:Product a owl:Class .
	
	lcdccore:Study a owl:Class .
	
	lcdccore:SubTheme a owl:Class .
	
	lcdccore:Subject a owl:Class .
	
	lcdccore:Theme a owl:Class .
	
	lcdccore:mainDataSet a owl:ObjectProperty .
	
	lcdccore:node a owl:ObjectProperty .
	
	lcdccore:obsInterval a owl:ObjectProperty .
	
	lcdccore:phase a owl:ObjectProperty .
	
	lcdccore:product a owl:ObjectProperty .
	
	lcdccore:specialisedObservation a owl:ObjectProperty .
	
	lcdccore:study a owl:ObjectProperty .
	
	lcdccore:subject a owl:ObjectProperty .
	
	lcdccore:subtheme a owl:ObjectProperty .
	
	lcdccore:theme a owl:ObjectProperty .
	
	lcdcobs:DatedObservation a owl:Class ;
	    rdfs:label "Dated Observation" ;
	    dc:description "Specialised cube observation for which a date is available." ;
	    apivc:uriTemplate "http://aehrc-ci.it.csiro.au/dataset/aibl/{linked}/theme/{theme}/subtheme/{subtheme}/phase/{phase}/subject/{subject}/date/{date}" ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:subClassOf lcdcobs:Observation .
	
	lcdcobs:DatedObservationGroup a owl:Class ;
	    rdfs:label "Dated Observation Group" ;
	    dc:description "Main cube observation group (and observation) for which a date is available: contains links to all the specialised dated cube observations." ;
	    apivc:uriTemplate "http://aehrc-ci.it.csiro.au/dataset/aibl/{linked}/phase/{phase}/subject/{subject}/date/{date}" ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:subClassOf lcdcobs:ObservationGroup .
	
	lcdcobs:endInstant a owl:ObjectProperty ;
	    rdfs:label "end date" ;
	    dc:description "The end date of the data collection." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" .
	
	lcdcobs:startInstant a owl:ObjectProperty ;
	    rdfs:label "start date" ;
	    dc:description "The start date of the data collection." ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" .
	
	interval:CalendarInterval a owl:Class .
	
	qb:DataSet a owl:Class .
	
	qb:Observation a owl:Class .
	
	lcdcobs:ObservationGroup a owl:Class ;
	    rdfs:label "Observation Group" ;
	    dc:description "Main cube observation group (and observation): contains links to all the specialised cube observations." ;
	    apivc:uriTemplate "http://aehrc-ci.it.csiro.au/dataset/aibl/{linked}/phase/{phase}/subject/{subject}" ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:subClassOf [ a owl:Restriction ;
	            owl:onProperty lcdccore:specialisedObservation ;
	            owl:someValuesFrom qb:Observation ],
	        [ a owl:Restriction ;
	            owl:onProperty lcdccore:mainDataSet ;
	            owl:someValuesFrom qb:DataSet ],
	        [ a owl:Restriction ;
	            owl:onProperty qb:specialisedObservation ;
	            owl:someValuesFrom lcdcobs:Observation ],
	        qb:ObservationGroup .
	
	interval:CalendarInstant a owl:Class .
	
	lcdcobs:Observation a owl:Class ;
	    rdfs:label "Observation" ;
	    dc:description "Specialised cube observation." ;
	    apivc:uriTemplate "http://aehrc-ci.it.csiro.au/dataset/aibl/{linked}/theme/{theme}/subtheme/{subtheme}/phase/{phase}/subject/{subject}" ;
	    rdfs:isDefinedBy "http://purl.org/sstats/lcdc/def/obs" ;
	    rdfs:subClassOf [ a owl:Restriction ;
	            owl:onProperty lcdccore:phase ;
	            owl:someValuesFrom lcdccore:Phase ],
	        [ a owl:Restriction ;
	            owl:onProperty lcdccore:node ;
	            owl:someValuesFrom lcdccore:Node ],
	        [ a owl:Restriction ;
	            owl:onProperty lcdccore:study ;
	            owl:someValuesFrom lcdccore:Study ],
	        [ a owl:Restriction ;
	            owl:onProperty qb:dataSet ;
	            owl:someValuesFrom qb:DataSet ],
	        [ a owl:Restriction ;
	            owl:onProperty lcdccore:theme ;
	            owl:someValuesFrom lcdccore:Theme ],
	        [ a owl:Restriction ;
	            owl:onProperty lcdccore:subject ;
	            owl:someValuesFrom lcdccore:Subject ],
	        qb:Observation .
 */
public class Obs {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/sstats/lcdc/def/obs#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    public static final ObjectProperty END_INSTANT = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/obs#endInstant" );

    public static final ObjectProperty START_INSTANT = m_model.createObjectProperty( "http://purl.org/sstats/lcdc/def/obs#startInstant" );

    public static final DatatypeProperty CUBE_OBS_MISSING = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#cubeObsMissing" );

    public static final DatatypeProperty DAY = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#day" );

    public static final DatatypeProperty END_DAY = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#endDay" );

    public static final DatatypeProperty END_MONTH = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#endMonth" );

    public static final DatatypeProperty END_YEAR = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#endYear" );

    public static final DatatypeProperty HOUR = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#hour" );

    public static final DatatypeProperty MINUTE = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#minute" );

    public static final DatatypeProperty MONTH = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#month" );

    public static final DatatypeProperty OBS_DATE_TIME = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#obsDateTime" );

    public static final DatatypeProperty OBS_DURATION = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#obsDuration" );

    public static final DatatypeProperty SECOND = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#second" );

    public static final DatatypeProperty START_DAY = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#startDay" );

    public static final DatatypeProperty START_MONTH = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#startMonth" );

    public static final DatatypeProperty START_YEAR = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#startYear" );

    public static final DatatypeProperty YEAR = m_model.createDatatypeProperty( "http://purl.org/sstats/lcdc/def/obs#year" );

    public static final OntClass DATED_OBSERVATION = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#DatedObservation" );

    public static final OntClass DATED_OBSERVATION_GROUP = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#DatedObservationGroup" );

    public static final OntClass INTERVAL_OBSERVATION = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#IntervalObservation" );

    public static final OntClass INTERVAL_OBSERVATION_GROUP = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#IntervalObservationGroup" );

    public static final OntClass OBSERVATION = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#Observation" );

    public static final OntClass OBSERVATION_GROUP = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#ObservationGroup" );

    public static final OntClass TIMED_OBSERVATION = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#TimedObservation" );

    public static final OntClass TIMED_OBSERVATION_GROUP = m_model.createClass( "http://purl.org/sstats/lcdc/def/obs#TimedObservationGroup" );

}
